apiVersion: v1
kind: Service
metadata:
  name: gpu-admission
  namespace: "FILLED_BY_THE_OPERATOR"
  labels:
    component: scheduler
    tier: control-plane
spec:
  selector:
    component: scheduler
    tier: control-plane
  ports:
  - name: gpu-operator-metrics
    port: 3456
    targetPort: 3456
    protocol: TCP
